config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
   resources :books, only: [:create, :index, :show, :edit, :update]
   resources :users, only: [:update, :index, :show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: {in: 1..200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, length: {in: 2..20}
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @book_re = current_user
      render 'index'
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @book_re = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'successfully.'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th><th><%= book.user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th><th><%= book.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(book.user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book_new, local:true do |f| %>
        <div class="form group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        </div>
        <div class="form group my-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
        </div>
        <%= f.submit 'Crate Book', class:"btn btn-success" %>
        <% end %>
    </div>

app/views/books/edit.html.erb
<div class='container'>
    <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2 class="mt-3">Editing Book</h2>
       <% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
     <%= form_with model:@book, local:true do |f| %>
     <div class="form group">
       <label for="book_title">Title</label>
       <%= f.text_field :title, autofocus: true, class:"form-control book_title", id:"book_title"%>
     </div>
     <div class="form group my-3">
       <label for="book_opinion">Opinion</label>
       <%= f.text_area :body, class:"form-control book_body", id:"book_body"%>
     </div>

     <%= f.submit "Update Book", class:"btn btn-success mb-3" %>
     <% end %>
     <%= link_to "Show",book_path(@book.id) %>
     |
     <%= link_to "Back",books_path %>
     </div>
    </div>
  </div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @book_re, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th><th><%= @book_re.name %></th>
            </tr>
            <tr>
              <th>Introduction</th><th><%= @book_re.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@book_re.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        </div>
        <div class="form group my-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
        </div>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
              <% end%>
            <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
      <%= flash[:notice] %>
  </div>
 <% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th><th><%= @book.user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th><th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@book.user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book_new, local:true do |f| %>
        <div class="form group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        </div>
        <div class="form group my-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
        </div>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
             <td>
               <%= link_to user_path(@book.user.id) do %>
               <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
               <br>
               <%= @book.user.name %>
               <% end %>
             </td>
             <td>
               <%= link_to book_path(@book.id) do %>
               <%= @book.title %>
               <% end %>
             </td>
             <td>
               <%= @book.body%>
             </td>
             <% if @book.user == current_user %>
             <td><%= link_to "Edit",edit_book_path(@book.id), class:"btn btn-sm btn-success"%></td>
             <td><%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm btn-danger" %></td>
             <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
     <div class='row'>
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
    <div class="container">
        <div class="row">
             <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
                 <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
                 <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
                 <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                 <p> about various books!</p>
                 <div class="btn-wrapper col-10 mx-auto">
                     <% if user_signed_in? %>
                     <div class="row">
                         <%= link_to user_path(current_user.id), class:"btn btn-info btn-sm btn-block mb-3 sign_in" do  %>
                         Log in
                         <% end %>
                     </div>
                     <div class="row">
                         <%= link_to user_path(current_user.id), class:"btn btn-success btn-sm btn-block sign_up" do  %>
                         Sign up
                         <% end %>
                     </div>
                     <% else %>
                     <div class="row">
                          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                     </div>
                     <div class="row">
                         <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
                     </div>
                     <% end %>
                 </div>
             </div>
        </div>
   </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user.id), class:"fas fa-home nav-link text-light" do %>
          Home
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class:"fas fa-users nav-link text-light" do %>
          Users
          <% end %>
        </li>
        <li>
          <%=link_to books_path, class:"fas fa-book-open nav-link text-light" do %>
          Books
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" do %>
          Log out
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to root_path, class:"fas fa-home nav-link text-light" do %>
          Home
          <% end %>
        </li>
        <li>
          <%= link_to home_about_path, class:"fas fa-link nav-link text-light" do %>
          About
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class:"fas fa-user-plus nav-link text-light" do %>
          Sign up
          <% end %>
        </li>
        <li>
         <%= link_to new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" do %>
         Log in
         <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>
  <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
         <p>CopyRight Infrstop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class='container'>
    <div class='row'>
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2 class="mt-3">User info</h2>
       <% if @user.errors.any? %>
  <%= @user.errors.count %>errors
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
     <%= form_with model:@user, local:true do |f| %>
     <div class="form group">
       <label for="inputName">Name</label>
       <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前"%>
     </div>
     <div class="form group my-3">
       <label for="inputImage ">Image</label>
       <%= f.attachment_field :profile_image, class:"form-control-file"%>
     </div>
     <div class="form group mb-3">
       <label for="user_introduction">Introduction</label>
       <%= f.text_area :introduction, class:"form-control introduction", id:"user_introduction", placeholder:"自己紹介文"%>
     </div>

     <%= f.submit "Update User", class:"btn btn-secondary" %>
     <% end %>
     </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th><th><%= @user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th><th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book_new, local:true do |f| %>
        <div class="form group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        </div>
        <div class="form group my-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
        </div>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Users</h2>
      <table class="table">
        <thead>
          <tr>
            <td>image</td>
            <td>name</td>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th><th><%= @user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th><th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book_new, local:true do |f| %>
        <div class="form group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title", id:"book_title" %>
        </div>
        <div class="form group my-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_body", id:"book_body" %>
        </div>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2 class="mt-3">Books</h2>
      <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
            <% end %></td>
          <td><%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %></td>
          <td><%= book.body %></td>
        </tr>
      </tbody>
      <% end %>
      </table>
    </div>




  </div>
</div>